
-- 🛡️ UNIVERSAL ACCESS RESTORE (v5.0): OPEN ALL DOORS
-- Run this in Supabase SQL Editor to kill ALL "Permission Denied" errors.

BEGIN;

-- 1. DISABLE RLS ON ALL TABLES (The Nuclear Option for Migration)
ALTER TABLE IF EXISTS public.studios DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.studio_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.halls DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.attendance_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.attendance_archive DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.student_subscriptions DISABLE ROW LEVEL SECURITY;

-- 2. GRANT ALL PRIVILEGES TO CLIENT-SIDE ANON KEY
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated;

-- 3. ENSURE COLUMNS EXIST FOR ATOMIC JSON SYNC
ALTER TABLE IF EXISTS public.students ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.staff ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.branches ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.groups ADD COLUMN IF NOT EXISTS data JSONB DEFAULT '{}'::jsonb;

COMMIT;

-- ✅ THE GRID IS OPEN. PERMISSIONS ARE NOW TRANSPARENT.
