'use server';

/**
 * SMS module rebuild, Phase 1 (docs/tasks.md — classcore_sms_module_prd.pdf
 * v1.3 §3/§4). Server Actions for the category → template model that
 * replaces the old hardcoded 7-key `settings.sms_templates` blob
 * (src/lib/settings-store.ts, still read by the current sms-manager page
 * and sms-service.ts — not touched by this phase; the UI cutover and the
 * old blob's removal are a follow-up once this is wired in and verified).
 *
 * First real use of the `{data,error}` convention from
 * docs/agents/api-contract.md — written new, so it follows that shape
 * from the start rather than the throw-on-error pattern older action
 * files use.
 */

import crypto from 'crypto';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { requireEffectivePermission } from '@/lib/permissions/enforce';
import type { DualAuthContext } from '@/lib/server-actions-auth';
import { ok, fail, type ActionResult } from '@/lib/action-result';

export type SmsCategory = {
    id: string;
    name: string;
    color: string | null;
    icon: string | null;
    moduleKey: string | null;
    enabled: boolean;
    createdAt: string;
};

export type SmsTemplate = {
    id: string;
    categoryId: string;
    name: string;
    textKa: string;
    textRu: string;
    textEn: string;
    triggerType: 'manual' | 'event';
    eventKey: string | null;
    recipientScope: 'all' | 'group' | 'branch' | 'person';
    recipientTargetId: string | null;
    status: 'draft' | 'active';
    frequencyLimitCount: number | null;
    frequencyLimitDays: number | null;
    isAutoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
};

type CategoryRow = {
    id: string; name: string; color: string | null; icon: string | null;
    module_key: string | null; enabled: boolean; created_at: string;
};

type TemplateRow = {
    id: string; category_id: string; name: string; text_ka: string; text_ru: string; text_en: string;
    trigger_type: 'manual' | 'event'; event_key: string | null;
    recipient_scope: 'all' | 'group' | 'branch' | 'person'; recipient_target_id: string | null;
    status: 'draft' | 'active'; frequency_limit_count: number | null; frequency_limit_days: number | null;
    is_auto_generated: boolean; created_at: string; updated_at: string;
};

function mapCategory(r: CategoryRow): SmsCategory {
    return { id: r.id, name: r.name, color: r.color, icon: r.icon, moduleKey: r.module_key, enabled: r.enabled, createdAt: r.created_at };
}

function mapTemplate(r: TemplateRow): SmsTemplate {
    return {
        id: r.id, categoryId: r.category_id, name: r.name, textKa: r.text_ka, textRu: r.text_ru, textEn: r.text_en,
        triggerType: r.trigger_type, eventKey: r.event_key, recipientScope: r.recipient_scope, recipientTargetId: r.recipient_target_id,
        status: r.status, frequencyLimitCount: r.frequency_limit_count, frequencyLimitDays: r.frequency_limit_days,
        isAutoGenerated: r.is_auto_generated, createdAt: r.created_at, updatedAt: r.updated_at,
    };
}

/**
 * Who performed a mutation, for sms_audit_log (PRD §9's audit journal —
 * "ვინ და როდის შეასრულა კონკრეტული მოქმედება"). Best-effort: an audit
 * row is never worth failing the actual mutation over.
 */
async function resolveActor(ctx: DualAuthContext): Promise<{ id: string | null; name: string | null }> {
    try {
        if (!ctx.isStaffToken) {
            const { data } = await ctx.client.auth.getUser();
            const meta = data?.user?.user_metadata as Record<string, unknown> | undefined;
            return { id: data?.user?.id ?? null, name: (meta?.full_name as string) || data?.user?.email || null };
        }
        if (!ctx.staffId) return { id: null, name: null };
        const { data } = await ctx.client.from('staff').select('first_name, last_name').eq('id', ctx.staffId).maybeSingle();
        const name = data ? [data.first_name, data.last_name].filter(Boolean).join(' ') : null;
        return { id: ctx.staffId, name: name || null };
    } catch {
        return { id: null, name: null };
    }
}

async function logAudit(ctx: DualAuthContext, action: string, targetType: 'category' | 'template', targetId: string, details?: Record<string, unknown>) {
    try {
        const actor = await resolveActor(ctx);
        await ctx.client.from('sms_audit_log').insert({
            org_id: ctx.orgId, actor_id: actor.id, actor_name: actor.name,
            action, target_type: targetType, target_id: targetId, details: details ?? null,
        });
    } catch {
        // Never fail the mutation over an audit-log write.
    }
}

/** Starter categories/templates seeded once per org, matching the current DEFAULT_SETTINGS.sms_templates text
 * (settings-store.ts) as a starting point. Existing per-studio customized text in that old blob does NOT carry
 * over here automatically — see docs/tasks.md's "SMS module PRD alignment" entry for why (Server Actions run
 * server-side and have no access to the old client-localStorage-backed settings blob's actual per-org values). */
const SEED_TEMPLATES: Array<{ name: string; eventKey: string | null; triggerType: 'manual' | 'event'; ka: string; ru: string; en: string }> = [
    { name: 'გადახდის შეხსენება', eventKey: 'payment_due', triggerType: 'manual',
        ka: 'გამარჯობა {name}, შეგახსენებთ, რომ გაქვთ გადასახდელი {plan}-ის საფასური. გთხოვთ დაფაროთ. პატივისცემით, {studio}.',
        ru: 'Здравствуйте {name}, напоминаем об оплате абонемента {plan}. Пожалуйста, внесите оплату. С уважением, {studio}.',
        en: 'Hello {name}, this is a reminder regarding the payment for your {plan} plan. Best regards, {studio}.' },
    { name: 'აბონემენტის ვადის ამოწურვა', eventKey: 'subscription_expiring', triggerType: 'event',
        ka: 'გამარჯობა {name}, გენატრებათ ვარჯიში? თქვენი აბონემენტი ({plan}) იწურება დღეს. გთხოვთ განაახლოთ.',
        ru: 'Здравствуйте {name}, соскучились по тренировкам? Ваш абонемент ({plan}) истекает сегодня. Пожалуйста, обновите его.',
        en: 'Hello {name}, miss training? Your plan ({plan}) expires today. Please renew it.' },
    { name: 'დაბადების დღის მილოცვა', eventKey: 'birthday', triggerType: 'event',
        ka: 'გამარჯობა {name}, გილოცავთ დაბადების დღეს! საუკეთესო სურვილებით, {studio}.',
        ru: 'Здравствуйте {name}, с днем рождения! С наилучшими пожеланиями, {studio}.',
        en: 'Happy Birthday {name}! Best wishes, {studio}.' },
];

async function seedDefaultCategoryIfEmpty(ctx: DualAuthContext): Promise<void> {
    const { count } = await ctx.client.from('sms_categories').select('id', { count: 'exact', head: true }).eq('org_id', ctx.orgId);
    if ((count ?? 0) > 0) return;

    const categoryId = crypto.randomUUID();
    const { error: catErr } = await ctx.client.from('sms_categories').insert({
        id: categoryId, org_id: ctx.orgId, name: 'ზოგადი', color: null, icon: null, module_key: null, enabled: true,
    });
    if (catErr) return;

    await ctx.client.from('sms_templates').insert(SEED_TEMPLATES.map(t => ({
        id: crypto.randomUUID(), org_id: ctx.orgId, category_id: categoryId, name: t.name,
        text_ka: t.ka, text_ru: t.ru, text_en: t.en, trigger_type: t.triggerType, event_key: t.eventKey,
        recipient_scope: 'all', recipient_target_id: null, status: 'active', is_auto_generated: true,
    })));
}

export async function listSmsCategoriesAction(): Promise<ActionResult<SmsCategory[]>> {
    const ctx = await requireEffectivePermission('canViewSMS');
    await seedDefaultCategoryIfEmpty(ctx);

    const { data, error } = await ctx.client.from('sms_categories').select('*').eq('org_id', ctx.orgId).order('created_at', { ascending: true });
    if (error) return fail('query_failed', error.message);
    return ok((data as CategoryRow[]).map(mapCategory));
}

const createCategorySchema = z.object({ name: z.string().trim().min(1), color: z.string().trim().optional(), icon: z.string().trim().optional() });

export async function createSmsCategoryAction(rawInput: unknown): Promise<ActionResult<SmsCategory>> {
    const input = createCategorySchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const id = crypto.randomUUID();
    const { data, error } = await ctx.client.from('sms_categories')
        .insert({ id, org_id: ctx.orgId, name: input.name, color: input.color || null, icon: input.icon || null, module_key: null, enabled: true })
        .select('*').single();
    if (error) return fail('insert_failed', error.message);

    await logAudit(ctx, 'category_created', 'category', id, { name: input.name });
    revalidatePath('/sms-manager');
    return ok(mapCategory(data as CategoryRow));
}

const toggleCategorySchema = z.object({ id: z.string().min(1), enabled: z.boolean() });

export async function toggleSmsCategoryAction(rawInput: unknown): Promise<ActionResult<void>> {
    const input = toggleCategorySchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const { error } = await ctx.client.from('sms_categories').update({ enabled: input.enabled }).eq('id', input.id).eq('org_id', ctx.orgId);
    if (error) return fail('update_failed', error.message);

    await logAudit(ctx, input.enabled ? 'category_enabled' : 'category_disabled', 'category', input.id);
    revalidatePath('/sms-manager');
    return ok(undefined);
}

const deleteCategorySchema = z.object({ id: z.string().min(1) });

export async function deleteSmsCategoryAction(rawInput: unknown): Promise<ActionResult<void>> {
    const input = deleteCategorySchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const { error } = await ctx.client.from('sms_categories').delete().eq('id', input.id).eq('org_id', ctx.orgId);
    if (error) return fail('delete_failed', error.message);

    await logAudit(ctx, 'category_deleted', 'category', input.id);
    revalidatePath('/sms-manager');
    return ok(undefined);
}

const listTemplatesSchema = z.object({ categoryId: z.string().min(1).optional() });

export async function listSmsTemplatesAction(rawInput?: unknown): Promise<ActionResult<SmsTemplate[]>> {
    const input = listTemplatesSchema.parse(rawInput ?? {});
    const ctx = await requireEffectivePermission('canViewSMS');

    let query = ctx.client.from('sms_templates').select('*').eq('org_id', ctx.orgId);
    if (input.categoryId) query = query.eq('category_id', input.categoryId);
    const { data, error } = await query.order('created_at', { ascending: true });
    if (error) return fail('query_failed', error.message);
    return ok((data as TemplateRow[]).map(mapTemplate));
}

const templateFieldsSchema = z.object({
    categoryId: z.string().min(1),
    name: z.string().trim().min(1),
    textKa: z.string().default(''),
    textRu: z.string().default(''),
    textEn: z.string().default(''),
    triggerType: z.enum(['manual', 'event']).default('manual'),
    eventKey: z.string().trim().optional().nullable(),
    recipientScope: z.enum(['all', 'group', 'branch', 'person']).default('all'),
    recipientTargetId: z.string().trim().optional().nullable(),
    frequencyLimitCount: z.number().int().positive().optional().nullable(),
    frequencyLimitDays: z.number().int().positive().optional().nullable(),
});

export async function createSmsTemplateAction(rawInput: unknown): Promise<ActionResult<SmsTemplate>> {
    const input = templateFieldsSchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const id = crypto.randomUUID();
    const { data, error } = await ctx.client.from('sms_templates').insert({
        id, org_id: ctx.orgId, category_id: input.categoryId, name: input.name,
        text_ka: input.textKa, text_ru: input.textRu, text_en: input.textEn,
        trigger_type: input.triggerType, event_key: input.eventKey || null,
        recipient_scope: input.recipientScope, recipient_target_id: input.recipientTargetId || null,
        status: 'active', is_auto_generated: false,
    }).select('*').single();
    if (error) return fail('insert_failed', error.message);

    await logAudit(ctx, 'template_created', 'template', id, { name: input.name });
    revalidatePath('/sms-manager');
    return ok(mapTemplate(data as TemplateRow));
}

const updateTemplateSchema = templateFieldsSchema.extend({ id: z.string().min(1), status: z.enum(['draft', 'active']).optional() });

export async function updateSmsTemplateAction(rawInput: unknown): Promise<ActionResult<SmsTemplate>> {
    const input = updateTemplateSchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const { data, error } = await ctx.client.from('sms_templates').update({
        category_id: input.categoryId, name: input.name,
        text_ka: input.textKa, text_ru: input.textRu, text_en: input.textEn,
        trigger_type: input.triggerType, event_key: input.eventKey || null,
        recipient_scope: input.recipientScope, recipient_target_id: input.recipientTargetId || null,
        ...(input.status ? { status: input.status } : {}),
        updated_at: new Date().toISOString(),
    }).eq('id', input.id).eq('org_id', ctx.orgId).select('*').single();
    if (error) return fail('update_failed', error.message);

    await logAudit(ctx, 'template_edited', 'template', input.id, { name: input.name });
    revalidatePath('/sms-manager');
    return ok(mapTemplate(data as TemplateRow));
}

const deleteTemplateSchema = z.object({ id: z.string().min(1) });

export async function deleteSmsTemplateAction(rawInput: unknown): Promise<ActionResult<void>> {
    const input = deleteTemplateSchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const { error } = await ctx.client.from('sms_templates').delete().eq('id', input.id).eq('org_id', ctx.orgId);
    if (error) return fail('delete_failed', error.message);

    await logAudit(ctx, 'template_deleted', 'template', input.id);
    revalidatePath('/sms-manager');
    return ok(undefined);
}

const duplicateTemplateSchema = z.object({ id: z.string().min(1) });

export async function duplicateSmsTemplateAction(rawInput: unknown): Promise<ActionResult<SmsTemplate>> {
    const input = duplicateTemplateSchema.parse(rawInput);
    const ctx = await requireEffectivePermission('canViewSMS');

    const { data: original, error: fetchErr } = await ctx.client.from('sms_templates').select('*').eq('id', input.id).eq('org_id', ctx.orgId).maybeSingle();
    if (fetchErr) return fail('query_failed', fetchErr.message);
    if (!original) return fail('not_found', 'Template not found');

    const row = original as TemplateRow;
    const id = crypto.randomUUID();
    const { data, error } = await ctx.client.from('sms_templates').insert({
        id, org_id: ctx.orgId, category_id: row.category_id, name: `${row.name} (copy)`,
        text_ka: row.text_ka, text_ru: row.text_ru, text_en: row.text_en,
        trigger_type: row.trigger_type, event_key: row.event_key,
        recipient_scope: row.recipient_scope, recipient_target_id: row.recipient_target_id,
        status: 'draft', frequency_limit_count: row.frequency_limit_count, frequency_limit_days: row.frequency_limit_days,
        is_auto_generated: false,
    }).select('*').single();
    if (error) return fail('insert_failed', error.message);

    await logAudit(ctx, 'template_duplicated', 'template', id, { fromId: input.id });
    revalidatePath('/sms-manager');
    return ok(mapTemplate(data as TemplateRow));
}
